typeset -U path cdpath fpath manpath
for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done

HELPDIR="/nix/store/358sk8371mkz87iq17kw4qcyyi6sps0k-zsh-5.9/share/zsh/$ZSH_VERSION/help"

source /nix/store/lja33bji6aahyvpr1s82wsjnhjd0nhq0-zsh-autosuggestions-0.7.1/share/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_STRATEGY=(history)


# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(git sudo)

ZSH_THEME=gallifrey
source $ZSH/oh-my-zsh.sh

# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="/home/will/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

# Set shell options
set_opts=(
  HIST_FCNTL_LOCK APPEND_HISTORY HIST_IGNORE_DUPS HIST_IGNORE_SPACE
  SHARE_HISTORY NO_EXTENDED_HISTORY NO_HIST_EXPIRE_DUPS_FIRST
  NO_HIST_FIND_NO_DUPS NO_HIST_IGNORE_ALL_DUPS NO_HIST_SAVE_NO_DUPS
)
for opt in "${set_opts[@]}"; do
  setopt "$opt"
done
unset opt set_opts

alias -- :q=exit
alias -- gpl='git pull'
alias -- la='ls -al'
alias -- nixcln='~/nixos-dotfiles/home-manager/nixcln.sh'
alias -- udnix='~/nixos-dotfiles/home-manager/udnix.sh'
source /nix/store/wjfysmv7d7mc00nh8ihn26k3q40fvk1b-zsh-syntax-highlighting-0.8.0/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main)

# Open buffer line in editor
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line

bindkey -s '^Xgc' 'gc -m ""\C-b'
